# Permalinks
permalink:           pretty

# Setup
title:               Todd Hendricks
tagline:             Data Science Musings
url:                 http://tahentx.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Todd Hendricks
  url:               https://twitter.com/toddintech
  email:             hendricks.ta@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/tahentx

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
